name: Release Please

on:
  push:
    branches: ["main"]

permissions:
  contents: write # 明確授權可以 Push Commit、打 Tag 與發 Release
  pull-requests: write # 授權可以在 PR 下方自動留言

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
